[theme]
base="light"
primaryColor = "#1c6f9d"        # Cor primária
backgroundColor = "#FFFFFF"     # Cor do fundo
secondaryBackgroundColor = "#F0F2F6"  # Cor de fundo secundária
textColor = "#000000"           # Cor do texto
font = "sans serif"             # Fonte (opções: 'sans serif', 'serif', 'monospace')

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501